# creates a pull request for a new build of the repository
name: Re-Build Repository

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "LG-CPFL"
          git config user.email "lg@clarkpanagakos.com.au"
        
      - name: Create new branch
        run: git checkout -f -b auto-branch

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "re-built repo"
          git remote -v
          git push -a
      
