name: Make a tarball

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  id-token: write

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tarball
        run: tar czf github-pages.tar.gz index.html dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: github-pages
            path: github-pages.tar.gz